#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// RCX Jarvis - ESP32-S3 DevKitC-1 N16R8
// Mic: INMP441, Speaker amp: MAX98357A
#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_METHOD_SIMPLEX

// INMP441
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_2
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_14
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_1

// MAX98357A
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_16
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_17
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_8

// ESP32-S3 DevKitC-1 onboard RGB + BOOT
#define BUILTIN_LED_GPIO GPIO_NUM_48
#define BOOT_BUTTON_GPIO GPIO_NUM_0

#endif // _BOARD_CONFIG_H_
